import {
  User,
  Driver,
  Ride,
  Transaction,
  Voucher,
  StudentRecord,
  ChatMessage,
} from "@/_types";

export const STUDENT_DATABASE: Record<string, StudentRecord> = {
  "20223723": {
    fullName: "Adefaka Mosimiloluwa",
    department: "Mathematics",
    level: "400 Level",
    phoneNumber: "+234 123 456 7890",
  },
  "20223702": {
    fullName: "Soremi Ayomide Olufolaranmi",
    department: "Computer Science",
    level: "400 Level",
    phoneNumber: "+234 812 345 6789",
  },
  "20221045": {
    fullName: "Ayomide Cole",
    department: "Agricultural Engineering",
    level: "200 Level",
    phoneNumber: "+234 803 456 7890",
  },
  "20220876": {
    fullName: "Funmi Peters",
    department: "Food Science & Technology",
    level: "400 Level",
    phoneNumber: "+234 810 234 5678",
  },
  "20230156": {
    fullName: "Chidera Okafor",
    department: "Mechanical Engineering",
    level: "100 Level",
    phoneNumber: "+234 901 234 5678",
  },
  "20210433": {
    fullName: "Blessing Adeyemi",
    department: "Biochemistry",
    level: "500 Level",
    phoneNumber: "+234 708 345 6789",
  },
};

export const MOCK_DRIVERS: Driver[] = [
  {
    id: "1",
    name: "Funmi Peters",
    plateNumber: "LA 909-BC",
    rating: 4.8,
    totalSeats: 4,
    occupiedSeats: 2,
    distance: 80,
    fare: 200,
    status: "available",
    image:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    verified: true,
    tricycleType: "yellow",
    online: true,
    verificationCode: "1234",
  },
  {
    id: "2",
    name: "Ayomide Cole",
    plateNumber: "OG 123-AA",
    rating: 4.9,
    totalSeats: 4,
    occupiedSeats: 1,
    distance: 120,
    fare: 200,
    status: "available",
    image:
      "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face",
    verified: true,
    tricycleType: "green",
    online: true,
    verificationCode: "5678",
  },
  {
    id: "3",
    name: "Bayo Adeniyi",
    plateNumber: "OG 456-CD",
    rating: 4.5,
    totalSeats: 4,
    occupiedSeats: 3,
    distance: 200,
    fare: 150,
    status: "available",
    image:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
    verified: true,
    tricycleType: "green",
    online: true,
    verificationCode: "9012",
  },
  {
    id: "4",
    name: "Kemi Ogunlade",
    plateNumber: "OG 789-EF",
    rating: 4.7,
    totalSeats: 4,
    occupiedSeats: 0,
    distance: 350,
    fare: 200,
    status: "available",
    image:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    verified: true,
    tricycleType: "yellow",
    online: true,
    verificationCode: "3456",
  },
  {
    id: "5",
    name: "Taiwo Ibrahim",
    plateNumber: "LA 321-GH",
    rating: 4.3,
    totalSeats: 4,
    occupiedSeats: 4,
    distance: 500,
    fare: 250,
    status: "busy",
    image:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    verified: false,
    tricycleType: "yellow",
    online: false,
    verificationCode: "7890",
  },
];

export const MOCK_RIDES: Ride[] = [
  {
    id: "1",
    date: "Oct 12, 2023 \u2022 09:45 AM",
    pickupLocation: "Jaja Hall, FUNAAB",
    destination: "Senate Building",
    fare: 200,
    status: "completed",
    driverName: "Funmi Peters",
    txId: "TX-101",
  },
  {
    id: "2",
    date: "Oct 10, 2023 \u2022 02:20 PM",
    pickupLocation: "School Clinic",
    destination: "Motion Ground",
    fare: 400,
    status: "completed",
    driverName: "Ayomide Cole",
    txId: "TX-102",
  },
  {
    id: "3",
    date: "Oct 08, 2023 \u2022 11:10 AM",
    pickupLocation: "Senate Building",
    destination: "Library Junction",
    fare: 200,
    status: "cancelled",
    driverName: "Bayo Adeniyi",
    txId: "TX-103",
  },
  {
    id: "4",
    date: "Oct 05, 2023 \u2022 08:30 AM",
    pickupLocation: "Ceremonial Gate",
    destination: "COLMAS",
    fare: 300,
    status: "completed",
    driverName: "Kemi Ogunlade",
    txId: "TX-104",
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "1",
    type: "ride",
    title: "Ride to Senate Bldg",
    amount: 200,
    isCredit: false,
    date: "Oct 12, 2023",
    status: "completed",
  },
  {
    id: "2",
    type: "ride",
    title: "Ride to Library Junction",
    amount: 200,
    isCredit: false,
    date: "Oct 08, 2023",
    status: "void",
  },
  {
    id: "3",
    type: "topup",
    title: "Wallet Top-up",
    amount: 5000,
    isCredit: true,
    date: "Oct 07, 2023",
    status: "completed",
  },
  {
    id: "4",
    type: "withdrawal",
    title: "Bank Withdrawal",
    amount: 2000,
    isCredit: false,
    date: "Oct 05, 2023",
    status: "completed",
  },
  {
    id: "5",
    type: "ride",
    title: "Ride to Ceremony Gate",
    amount: 150,
    isCredit: false,
    date: "Oct 03, 2023",
    status: "completed",
  },
  {
    id: "6",
    type: "crypto",
    title: "Crypto Swap (BTC)",
    amount: 10000,
    isCredit: true,
    date: "Oct 01, 2023",
    status: "completed",
  },
  {
    id: "7",
    type: "ride",
    title: "Ride to COLMAS",
    amount: 300,
    isCredit: false,
    date: "Sep 28, 2023",
    status: "completed",
  },
];

export const MOCK_VOUCHERS: Voucher[] = [
  {
    id: "1",
    code: "NEWSTUDENT",
    discount: 50,
    description: "\u20A650 off your first ride",
    expiresAt: "2024-12-31",
  },
  {
    id: "2",
    code: "KEKESAFE",
    discount: 100,
    description: "\u20A6100 off any campus ride",
    expiresAt: "2024-06-30",
  },
  {
    id: "3",
    code: "FUNAAB2024",
    discount: 75,
    description: "\u20A675 off - Welcome back!",
    expiresAt: "2024-03-31",
  },
];

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: "1",
    text: "Hello! I'm on my way to your pickup location.",
    sender: "driver",
    timestamp: "Just now",
  },
];

export const AI_RESPONSES: string[] = [
  "Hi there! I'm CID Support AI. How can I help you today?",
  "I can help you with ride bookings, wallet issues, or account settings. What do you need?",
  "Let me look into that for you. One moment please...",
  "I've found some information that might help. Would you like me to connect you with a live agent?",
  "Your ride history shows your last trip was completed successfully. Is there anything specific about it?",
  "For payment issues, I recommend checking your wallet balance first. You can top up via Monnify or Crypto.",
  "I'm connecting you with a live support agent now. Please hold on...",
];
